{% set name = "pysqlite3" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysqlite3-{{ version }}.tar.gz
  sha256: 3bbddd291e21c83670034f17a13edd0e0ef6ef1a53764ecdcb322d36d7302287

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - sqlite
  host:
    - pip
    - python >=3.0
    - sqlite
  run:
    - python >=3.0
    - sqlite

test:
  imports:
    - pysqlite3

about:
  home: https://github.com/coleifer/pysqlite3
  summary: DB-API 2.0 interface for Sqlite 3.x
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - psortos
    - mxr-conda
